[2024-07-06 19:38:32,532] 224 werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[2024-07-06 19:38:32,533] 224 werkzeug - INFO - [33mPress CTRL+C to quit[0m
[2024-07-06 19:38:39,207] 224 werkzeug - INFO - 127.0.0.1 - - [06/Jul/2024 19:38:39] "GET / HTTP/1.1" 200 -
[2024-07-06 19:38:43,300] 224 werkzeug - INFO - 127.0.0.1 - - [06/Jul/2024 19:38:43] "GET /predict HTTP/1.1" 200 -
[2024-07-06 19:38:53,811] 69 root - INFO - Dataframe Gathered
[2024-07-06 19:38:53,813] 1744 app - ERROR - Exception on /predict [POST]
Traceback (most recent call last):
  File "C:\Users\kisha\Desktop\myproject\venv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\kisha\Desktop\myproject\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\kisha\Desktop\myproject\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\kisha\Desktop\myproject\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "app.py", line 33, in predict_datapoint
    pred=predict_pipeline(final_data)
TypeError: 'PredictPipeline' object is not callable
[2024-07-06 19:38:53,818] 224 werkzeug - INFO - 127.0.0.1 - - [06/Jul/2024 19:38:53] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
